Repository micronaut-projects/micronaut-rss, pull requests merged in 2020-11, with the labels that each got.

#53 Bump up micronaut test to 2.2.1
  gradle.properties
Labels: type: dependency-upgrade

#55 Add @NonNull annotation to builder methods
  itunespodcast/src/main/java/io/micronaut/rss/itunespodcast/ItunesPodcast.java
  itunespodcast/src/main/java/io/micronaut/rss/itunespodcast/ItunesPodcastEpisode.java
  itunespodcast/src/main/java/io/micronaut/rss/itunespodcast/ItunesPodcastOwner.java
  rss-core/src/main/java/io/micronaut/rss/RssChannel.java
  rss-core/src/main/java/io/micronaut/rss/RssChannelImage.java
  rss-core/src/main/java/io/micronaut/rss/RssItem.java
  rss-core/src/main/java/io/micronaut/rss/RssItemEnclosure.java
Labels: type: improvement

#61 feat: add json feed core module
  itunespodcast/src/main/java/io/micronaut/rss/itunespodcast/ItunesPodcast.java
  jsonfeed-core/build.gradle
  jsonfeed-core/src/main/java/io/micronaut/rss/jsonfeed/JsonFeed.java
  jsonfeed-core/src/main/java/io/micronaut/rss/jsonfeed/JsonFeedAttachment.java
  jsonfeed-core/src/main/java/io/micronaut/rss/jsonfeed/JsonFeedAuthor.java
  jsonfeed-core/src/main/java/io/micronaut/rss/jsonfeed/JsonFeedItem.java
  jsonfeed-core/src/main/java/io/micronaut/rss/jsonfeed/JsonHub.java
  jsonfeed-core/src/main/java/io/micronaut/rss/jsonfeed/package-info.java
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/ApplicationContextSpecification.groovy
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/ConfigurationFixture.groovy
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/JsonFeedAttachmentSpec.groovy
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/JsonFeedAuthorSpec.groovy
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/JsonFeedItemSpec.groovy
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/JsonFeedSpec.groovy
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/JsonHubSpec.groovy
  rss-language/src/main/java/io/micronaut/rss/language/RssLanguage.java
  settings.gradle
  src/main/docs/guide/introduction.adoc
  src/main/docs/guide/jsonfeed.adoc
  src/main/docs/guide/toc.yml
Labels: type: improvement

#62 feat: JSON Feed endpoint
  jsonfeed/build.gradle
  jsonfeed/src/main/java/io/micronaut/rss/jsonfeed/http/JsonFeedController.java
  jsonfeed/src/main/java/io/micronaut/rss/jsonfeed/http/JsonFeedControllerConfiguration.java
  jsonfeed/src/main/java/io/micronaut/rss/jsonfeed/http/JsonFeedControllerConfigurationProperties.java
  jsonfeed/src/main/java/io/micronaut/rss/jsonfeed/http/JsonFeedProvider.java
  jsonfeed/src/main/java/io/micronaut/rss/jsonfeed/http/package-info.java
  jsonfeed/src/test/groovy/io/micronaut/rss/jsonfeed/http/ApplicationContextSpecification.groovy
  jsonfeed/src/test/groovy/io/micronaut/rss/jsonfeed/http/ConfigurationFixture.groovy
  jsonfeed/src/test/groovy/io/micronaut/rss/jsonfeed/http/EmbeddedServerSpecification.groovy
  jsonfeed/src/test/groovy/io/micronaut/rss/jsonfeed/http/JsonFeedControllerConfigurationSpec.groovy
  jsonfeed/src/test/groovy/io/micronaut/rss/jsonfeed/http/JsonFeedControllerParamsSpec.groovy
  jsonfeed/src/test/groovy/io/micronaut/rss/jsonfeed/http/JsonFeedControllerPathSpec.groovy
  jsonfeed/src/test/groovy/io/micronaut/rss/jsonfeed/http/JsonFeedControllerSpec.groovy
  jsonfeed/src/test/java/io/micronaut/rss/jsonfeed/http/ExampleJsonFeedProvider.java
  jsonfeed/src/test/resources/application.yml
  settings.gradle
  src/main/docs/guide/jsonfeed.adoc
  src/main/docs/guide/jsonfeed/jsonfeedhttp.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#63 doc: add warning about blocking i/o
  src/main/docs/guide/jsonfeed/jsonfeedhttp.adoc
Labels: type: docs

#64 [rss] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#65 [rss] Update common files for branch 2.1.x
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: relates-to: build

#67 [rss] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/release-notes.yml
Labels: relates-to: build

#68 [rss] Update common files for branch 2.1.x
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/release-notes.yml
Labels: relates-to: build

#72 github actions: bump up create-pull-request to 3.5.1
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#73 fix: correct rfc 3339 pattern
  jsonfeed-core/src/main/java/io/micronaut/rss/jsonfeed/JsonFeedItem.java
  jsonfeed-core/src/test/groovy/io/micronaut/rss/jsonfeed/JsonFeedItemSpec.groovy
Labels: type: bug
