Repository micronaut-projects/micronaut-rss, pull requests merged in 2020-08, with the labels that each got.

#33 refactor: make method RssLanguage:of static
  rss-core/src/main/java/io/micronaut/rss/RssLanguage.java
  rss-core/src/test/groovy/io/micronaut/rss/RssLanguageSpec.groovy
Labels: type: improvement

#32 bump up to gradle 6.6
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#34 refactor: rename explicit not explict
  itunespodcast/src/main/java/io/micronaut/rss/itunespodcast/DefaultItunesPodcastRenderer.java
  itunespodcast/src/main/java/io/micronaut/rss/itunespodcast/ItunesPodcast.java
  itunespodcast/src/main/java/io/micronaut/rss/itunespodcast/ItunesPodcastEpisode.java
  itunespodcast/src/test/java/io/micronaut/rss/itunespodcast/DefaultRssFeedProvider.java
Labels: type: improvement

#38 [rss] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#41 [rss] Update common files for branch master
  .github/workflows/release-notes.yml
Labels: relates-to: build

#42 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade
